// network, server request using axios  to fetch movie data //
const fetchData = async (searchTerm) => { // helper function
   const response = await axios.get('http://www.omdbapi.com/', {
      params: {
         apikey: '90d486a',
         s: searchTerm 
      }
   });
   console.log(response.data);
};

// selecting search input for event listener //
const input = document.querySelector('input');

let timeoutId; // id generated by setTimeout function //
const onInput =  (event) => {
   // magic code 
   if (timeoutId){
      clearTimeout(timeoutId);
   }
   timeoutId = setTimeout(() => {
      fetchData(event.target.value);
   }, 500);
}; 
// add eventListener
input.addEventListener('input', onInput);

